### ISSUE TITLE
Tell me how to report my incident to the local police

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#13]
As a cyclist reporting an incident, I want to be reminded when and how I can report my incident to the police, and what it’s likely to involve, so that I can decide whether to take my report further.

Related to #12.

---

Reminders could be:
* Shown inline on the reporting form (there’s already a warning about reporting injuries near the top of the reporting form – maybe it could be hidden _until_ we know someone’s been injured?)
* Shown on the confirmation / success page.
* Sent as part of the confirmation email (#15).

Ideally the reminder would include:

* Criteria for when you should contact the police (ie: if anyone was injured)
* Explanation that you _really should_ do this – not only does it help build more accurate statistics for decision-makers, but it’s also a _legal responsibility_.
* A link to the most useful page on the police website (or, if not, their homepage) to start your report.

Will require police boundary data in MapIt, so we can look up the police force covering the incident location.

**Comment by LouiseMySociety** [comment]
Links to: https://waffle.io/mysociety/better-cities/cards/5b5f3dd8d4f718001b7b83f8

**Comment by dracos** [comment]
In google doc, Myfs says, about whther to have police message in confirmation email: "OK this is tricky - because if we include the link to the police here, it may distract from the confirmation. If we only include it on the confirmation success screen, we don't give people the chance to change their minds and not submit to Collideoscope, but still report to the police. On balance I think we should include it in both places."

Anyway, wording for it, wherever it is, is therefore under this feature:

> Should I report my incident to the police?
> ALL incidents resulting in injury and SOME cases involving damage to property must be reported to the police under Section 170 of the Road Traffic Act 1988. Where a car or other motorised vehicle is involved, it is the duty of its driver to make the report, but we recommend that cyclists also file a report in case the driver neglects to do so.
> Your local police force is [name of police force] and you can find details of how to make a report to them here. 
> See our FAQ on making a good police report
