### ISSUE TITLE
Fix category dropdown on front end

### ISSUE THREAD

**Issue by dracos** [mysociety/collideoscope#23]
The status/category filters aren't displaying correctly:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/4776/43653580-61f0c13e-9740-11e8-8bce-45bc21f86876.png">

<img width="461" alt="image" src="https://user-images.githubusercontent.com/4776/43653527-3f562b1e-9740-11e8-8d0a-b17b37f40b8f.png">

**Comment by davea** [comment]
The display of the items is now fixed: 

<img width="381" alt="image" src="https://user-images.githubusercontent.com/4776/43653770-f678e7fa-9740-11e8-9919-d5509472f339.png">

However I'm not sure of the best way to fix the slightly odd display of the category names.

One option is to just prettify the displayed names a bit:

<img width="351" alt="image" src="https://user-images.githubusercontent.com/4776/43655059-705b47f8-9745-11e8-83f9-202ae57eb3b0.png">

Alternatively we replace the slightly superfluous open/closed/fixed status dropdown and split the category field into two, just like we ask when making a report:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/4776/43655571-09696320-9747-11e8-81eb-10faf343c02b.png">

<img width="355" alt="image" src="https://user-images.githubusercontent.com/4776/43655578-0f47702a-9747-11e8-8c1c-6569ffd8587f.png">


I prefer the second option, as I think it makes more sense from a UI point of view. I'll proceed with implementing that unless anyone says otherwise!
