### ISSUE TITLE
Mobile: Not able to click the Home button after placing a pin on the map

### ISSUE THREAD

**Issue by LouiseMySociety** [mysociety/collideoscope#44]
After I have positioned my pin on a map I can not click the home button in the top left of the screen as the try again option blocks it out.

**Comment by LouiseMySociety** [comment]
![home button Collideoscope.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aec706e465939001342d64d/125516c66e82c728ace21e0d46e09b9726c281bc9bfdb04de47eff98254f23762617a0246080a164fd52690e050a1de853524d41f4ab8f79afb36f26d95409eb846f5874c76e12a8bad04dad1da862da11d1e9e1d30695aa2f2ff58a86453f1b061c8ef85e31a09b42cf5fe406.png)

**Comment by dracos** [comment]
After clicking on the map to set a pin, the Home button is still clickable, fwiw :) For it not to be clickable, you also have to hit "OK" to confirm the pin placement, the page then scrolls down to the form, and then you scroll back up to the map. If instead of scrolling you click the 'Map' arrow it scrolls back up and is all clickable again. Also clicking "Try again" it all becomes clickable. Possible solutions:
* It spots the scroll back up to top and acts the same as if you'd clicked on Map (meh, don't want to start listening to scroll events);
* Make it impossible to scroll back up to map, only clicking the Map link will do it, by adjusting the height of `map_box` appropriately - map would move in the little faded out preview, and might not be clear how to get back up should you wish to, - other than that, does work nicely though;
* Make the modal Try Again start 30px from the top instead of 0px so it's not covering the banner (seems easiest!). PR at https://github.com/mysociety/fixmystreet/pull/2223
