### ISSUE TITLE
Better explanation of how you can get and use statistics

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/collideoscope#47]
At the moment, the Statistics item in the menu leads to  https://www.collideoscope.org.uk/reports.
However, as one of our main messages now is that people can use the stats, I think we need a better explanation of exactly how. Maybe like this:
1. Rename current statistics page 'all reports'. 
2. Create new statistics page with:
i) An explanation of all the data on the site - where does it come from, why might it be useful, how can it be used - ie by campaigning groups, road safety organisations, councils, and individuals?
ii) How to get this data (am I right in thinking that you can only get the whole dataset by arrangement with us?)
iii) Explanation of alerts

3. Add link to new page from the all reports page.

Happy to provide some copy if the relevant people can confirm this is a good idea (and tell me some facts to include).

**Comment by MyfanwyNixon** [comment]
That'd be nice - worth thinking about the users here. We've airily talked about researchers, cycling campaigners and individual residents (for want of a better word): perhaps @zarino has more background from his chats over what they'd find it useful to be able to self-serve? Can we offer any API or data downloads?

**Comment by zarino** [comment]
> Rename current statistics page 'all reports'.
> […]
> Or replace all reports page with something more like fixmystreet.com/reports?

Yes! What @dracos said. I’m imagining something like a cross between the simple layout of `fixmystreet.com/reports` and the interactive filtering/grouping of the council-only stats dashboards at `fixmystreet.com/reports/<area>/summary`.

We’ve not done much yet to wireframe what such a page would contain, but the ticket I _think_ it really comes under is https://github.com/mysociety/collideoscope/issues/18.

> We've airily talked about researchers, cycling campaigners and individual residents (for want of a better word): perhaps @zarino has more background from his chats over what they'd find it useful to be able to self-serve?

Notes from the research summary:

* Filtering reports by who/what was involved in the collision (eg: pedestrian, van, heavy goods vehicle) would help campaigners pull out statistics for specific audiences or decision-makers.
* Filtering or grouping by ward/constituency would help campaigners communicate the scale of safety issues in a councillor or MP’s area, and in a way that could more easily be compared with other, similar areas, elsewhere.

"Researchers" is a bit vague, so I’ve mostly been thinking about cycling campaigners, because they’re _already_ actively working with this type of data. Some will have good statistical skills (using things like Fusion Tables or Excel to find patterns in datasets like STATS19), others will only just be starting out with the idea of using _data_ to back up their in-person campaigns, so just seeing a simple online graph or something would be a _huge_ help to them.

Most of them will have a particular _angle_ they’re interested in – be it a mode of transport (eg: HGVs) or an area (eg: this particular councillor’s ward) or a comparison between two rival cities. So if we can make the `/reports` page support these through very high-level slicing-and-dicing, and then leave everything else to a big data dump, that’d be the ideal world.

Council staff / safety staff might find their way onto this page, and their needs will be fairly similar to the campaigners – they’ll either be wanting to see _generally_ how their area performs, or they’ll want to quickly get to a map view, so they can investigate incidents around a particular road or intersection they’re looking at modifying/upgrading. I’d be surprised if council staff want to download the data for offline analysis.

Individual cyclists might also come to this page, looking for a cursory idea of how safe their area is. They might just have reported an incident themselves, or they might be intrigued at how their local area compares to another nearby one, or one they’re planning on visiting. So having something _super simple_ for them to feel like they’re getting information out (sort of akin to the zero-config `fixmystreet.com/reports` page, which imparts a lot of high-level information without demanding much effort from the viewer) is probably best for these folks. Then, if they’re really geeky 😉 they might start filtering/investigating further, which moves them, essentially, into the "cycling campaigner" camp.

**Comment by dracos** [comment]
Doing as new report/stats page, covered elsewhere.
